protocol: 'https:'
host: 'kasajima-tech'
sitetitle: '赤阪のエンジニアの日常'
sitesubtitle: '4kディスプレイは最高'
links:
- text: 'top'
  href: '/?page=top'
- text: '開発日誌(ブログ)'
  href: '/?post'
- text: '外部サイト'
  href: './'
  sublinks:
  - text: 'GitHub'
    href: 'https://github.com/kasajimakengo/bashcms2_contents'
  - text: 'おみくじLinebot'
    href: 'https://qr-official.line.me/sid/L/601lngwt.png'
sociallinks:
- icon: 'fa-twitter-square'
  href: 'https://twitter.com/tyappei'
- icon: 'fa-youtube-square'
  href: ''
- icon: 'fa-github-square'
  href: ''
- icon: 'fa-graduation-cap'
  href: ''
hatena: '@'
twitter: 'tyappei'
line: '@'
facebook: '@'
pocket: '@'
